table DateTable
	lineageTag: 91c7b083-b9aa-400a-a1d4-3502fe4b645e
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: 4ed75c09-f0d5-4cf0-b8ca-6fa64832b070
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 46f5acf5-68eb-4ad7-9e79-774083493815
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Start of Year'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7bd0b938-ea7c-4290-87b1-e868b4533529
		summarizeBy: none
		sourceColumn: Start of Year

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'End of Year'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a24cec56-aa61-47b5-abe1-b23cef2ab577
		summarizeBy: none
		sourceColumn: End of Year

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Month
		dataType: int64
		formatString: 0
		lineageTag: aa01b5c6-d8b5-45ad-952e-ff97d11fdcd4
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Start of Month'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b93df028-35d2-4646-806e-f29e0227d357
		summarizeBy: none
		sourceColumn: Start of Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'End of Month'
		dataType: dateTime
		formatString: Long Date
		lineageTag: de9924d3-a72b-44b7-a880-00f5f99401a8
		summarizeBy: none
		sourceColumn: End of Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Days in Month'
		dataType: int64
		formatString: 0
		lineageTag: ad4843bb-54ae-4bfa-922e-8f63adf5d855
		summarizeBy: none
		sourceColumn: Days in Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 698cf8b7-21cb-4ff4-a36f-c5ef3637b524
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column 'Day Name'
		dataType: string
		lineageTag: e2b8b700-3755-4368-8bba-b43a3ad00898
		summarizeBy: none
		sourceColumn: Day Name

		annotation SummarizationSetBy = Automatic

	column 'Day of Week'
		dataType: int64
		formatString: 0
		lineageTag: d393033f-fe1a-4e07-a944-fc2989f3faad
		summarizeBy: none
		sourceColumn: Day of Week

		annotation SummarizationSetBy = Automatic

	column 'Day of Year'
		dataType: int64
		formatString: 0
		lineageTag: 0bc8f161-012d-4fff-9c87-b75525d381d5
		summarizeBy: none
		sourceColumn: Day of Year

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 7f3ccece-34cc-49ba-a523-fb2588f80ce4
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: 1227e5f5-6c38-4cec-9ee0-fcf1081ebcf2
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column 'Start of Quarter'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ba619e00-03a3-4923-8e15-fdc23085d6b2
		summarizeBy: none
		sourceColumn: Start of Quarter

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'End of Quarter'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 62bcb06b-0cc2-4987-8683-cfed0dc4801c
		summarizeBy: none
		sourceColumn: End of Quarter

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Week of Year'
		dataType: int64
		formatString: 0
		lineageTag: 5839a7b4-7a56-4fa3-a09d-3dcb5c68cef6
		summarizeBy: none
		sourceColumn: Week of Year

		annotation SummarizationSetBy = Automatic

	column 'Week of Month'
		dataType: int64
		formatString: 0
		lineageTag: 8c524fcc-f9f5-4416-b965-b4ea0d844293
		summarizeBy: none
		sourceColumn: Week of Month

		annotation SummarizationSetBy = Automatic

	column 'Start of Week'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e0ad70b4-cb11-4f64-b430-0286c6d8616d
		summarizeBy: none
		sourceColumn: Start of Week

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'End of Week'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 06b89911-5ce4-49f8-8f24-6ea1d9628bd7
		summarizeBy: none
		sourceColumn: End of Week

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal Year'
		dataType: int64
		formatString: 0
		lineageTag: 563b8b4d-5e38-423e-b9d7-b9c30e98d654
		summarizeBy: none
		sourceColumn: Fiscal Year

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter'
		dataType: int64
		formatString: 0
		lineageTag: e1f3b183-86e8-4c85-ba27-10b080256507
		summarizeBy: none
		sourceColumn: Fiscal Quarter

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Month'
		dataType: int64
		formatString: 0
		lineageTag: 5ad0c9d9-cffe-4dc8-8477-0d4220bf3d57
		summarizeBy: none
		sourceColumn: Fiscal Month

		annotation SummarizationSetBy = Automatic

	column 'Day Offset'
		dataType: int64
		formatString: 0
		lineageTag: d2468e0f-6269-4a9d-83d1-1112306d911b
		summarizeBy: none
		sourceColumn: Day Offset

		annotation SummarizationSetBy = Automatic

	column 'Month Offset'
		dataType: int64
		formatString: 0
		lineageTag: 6b894e34-2315-477e-bacb-d511cdb6a5c1
		summarizeBy: none
		sourceColumn: Month Offset

		annotation SummarizationSetBy = Automatic

	column 'Year Offset'
		dataType: int64
		formatString: 0
		lineageTag: 5fb50e01-10e7-4339-858f-d6e691818dff
		summarizeBy: none
		sourceColumn: Year Offset

		annotation SummarizationSetBy = Automatic

	column 'Quarter Offset'
		dataType: int64
		formatString: 0
		lineageTag: 9a364f14-8dd6-4e4a-8fe1-58d52f74c098
		summarizeBy: none
		sourceColumn: Quarter Offset

		annotation SummarizationSetBy = Automatic

	column Year-Month
		dataType: string
		lineageTag: 2567a4e1-0ea1-4408-a9ff-16dbd5ad3d4f
		summarizeBy: none
		sourceColumn: Year-Month

		annotation SummarizationSetBy = Automatic

	column 'Year-Month Code'
		dataType: int64
		formatString: 0
		lineageTag: c96fc5c2-8f21-4200-9ff4-0b2f2f17b937
		summarizeBy: none
		sourceColumn: Year-Month Code

		annotation SummarizationSetBy = Automatic

	column 'First Day of Month' = DATE( YEAR([Date]), MONTH([Date]), 1)
		formatString: General Date
		lineageTag: 8e51aa4e-cee4-4396-aa55-c1829b1f1c40
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition DateTable = m
		mode: import
		source =
				let
				    // configurations start
				    //Today=Date.From(DateTime.LocalNow()), // today's date
				    Today = DateTimeZone.From(DateTimeZone.UtcNow()),
				    FromYear = 2010, // set the start year of the date dimension. dates start from 1st of January of this year
				    ToYear=2030, // set the end year of the date dimension. dates end at 31st of December of this year
				    StartofFiscalYear=7, // set the month number that is start of the financial year. example; if fiscal year start is July, value is 7
				    firstDayofWeek=Day.Monday, // set the week's start day, values: Day.Monday, Day.Sunday....
				    // configuration end
				    FromDate=#date(FromYear,1,1),
				    ToDate=#date(ToYear,12,31),
				    Source=List.Dates(
				        FromDate,
				        Duration.Days(ToDate-FromDate)+1,
				        #duration(1,0,0,0)
				    ),
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Date"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}}),
				    #"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Inserted Start of Year" = Table.AddColumn(#"Inserted Year", "Start of Year", each Date.StartOfYear([Date]), type date),
				    #"Inserted End of Year" = Table.AddColumn(#"Inserted Start of Year", "End of Year", each Date.EndOfYear([Date]), type date),
				    #"Inserted Month" = Table.AddColumn(#"Inserted End of Year", "Month", each Date.Month([Date]), Int64.Type),
				    #"Inserted Start of Month" = Table.AddColumn(#"Inserted Month", "Start of Month", each Date.StartOfMonth([Date]), type date),
				    #"Inserted End of Month" = Table.AddColumn(#"Inserted Start of Month", "End of Month", each Date.EndOfMonth([Date]), type date),
				    #"Inserted Days in Month" = Table.AddColumn(#"Inserted End of Month", "Days in Month", each Date.DaysInMonth([Date]), Int64.Type),
				    #"Inserted Day" = Table.AddColumn(#"Inserted Days in Month", "Day", each Date.Day([Date]), Int64.Type),
				    #"Inserted Day Name" = Table.AddColumn(#"Inserted Day", "Day Name", each Date.DayOfWeekName([Date]), type text),
				    #"Inserted Day of Week" = Table.AddColumn(#"Inserted Day Name", "Day of Week", each Date.DayOfWeek([Date],firstDayofWeek), Int64.Type),
				    #"Inserted Day of Year" = Table.AddColumn(#"Inserted Day of Week", "Day of Year", each Date.DayOfYear([Date]), Int64.Type),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Day of Year", "Month Name", each Date.MonthName([Date]), type text),
				    #"Inserted Quarter" = Table.AddColumn(#"Inserted Month Name", "Quarter", each Date.QuarterOfYear([Date]), Int64.Type),
				    #"Inserted Start of Quarter" = Table.AddColumn(#"Inserted Quarter", "Start of Quarter", each Date.StartOfQuarter([Date]), type date),
				    #"Inserted End of Quarter" = Table.AddColumn(#"Inserted Start of Quarter", "End of Quarter", each Date.EndOfQuarter([Date]), type date),
				    #"Inserted Week of Year" = Table.AddColumn(#"Inserted End of Quarter", "Week of Year", each Date.WeekOfYear([Date],firstDayofWeek), Int64.Type),
				    #"Inserted Week of Month" = Table.AddColumn(#"Inserted Week of Year", "Week of Month", each Date.WeekOfMonth([Date],firstDayofWeek), Int64.Type),
				    #"Inserted Start of Week" = Table.AddColumn(#"Inserted Week of Month", "Start of Week", each Date.StartOfWeek([Date],firstDayofWeek), type date),
				    #"Inserted End of Week" = Table.AddColumn(#"Inserted Start of Week", "End of Week", each Date.EndOfWeek([Date],firstDayofWeek), type date),
				    FiscalMonthBaseIndex=13-StartofFiscalYear,
				    adjustedFiscalMonthBaseIndex=if(FiscalMonthBaseIndex>=12 or FiscalMonthBaseIndex<0) then 0 else FiscalMonthBaseIndex,
				    #"Added Custom" = Table.AddColumn(#"Inserted End of Week", "FiscalBaseDate", each Date.AddMonths([Date],adjustedFiscalMonthBaseIndex)),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"FiscalBaseDate", type date}}),
				    #"Inserted Year1" = Table.AddColumn(#"Changed Type1", "Year.1", each Date.Year([FiscalBaseDate]), Int64.Type),
				    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Year1",{{"Year.1", "Fiscal Year"}}),
				    #"Inserted Quarter1" = Table.AddColumn(#"Renamed Columns1", "Quarter.1", each Date.QuarterOfYear([FiscalBaseDate]), Int64.Type),
				    #"Renamed Columns2" = Table.RenameColumns(#"Inserted Quarter1",{{"Quarter.1", "Fiscal Quarter"}}),
				    #"Inserted Month1" = Table.AddColumn(#"Renamed Columns2", "Month.1", each Date.Month([FiscalBaseDate]), Int64.Type),
				    #"Renamed Columns3" = Table.RenameColumns(#"Inserted Month1",{{"Month.1", "Fiscal Month"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns3",{"FiscalBaseDate"}),
				    #"Inserted Age" = Table.AddColumn(#"Removed Columns", "Age", each [Date]-Today, type duration),
				    #"Extracted Days" = Table.TransformColumns(#"Inserted Age",{{"Age", Duration.Days, Int64.Type}}),
				    #"Renamed Columns4" = Table.RenameColumns(#"Extracted Days",{{"Age", "Day Offset"}}),
				    #"Added Custom1" = Table.AddColumn(#"Renamed Columns4", "Month Offset", each (([Year]-Date.Year(Today))*12)
				+([Month]-Date.Month(Today))),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom1",{{"Month Offset", Int64.Type}}),
				    #"Added Custom2" = Table.AddColumn(#"Changed Type2", "Year Offset", each [Year]-Date.Year(Today)),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom2",{{"Year Offset", Int64.Type}}),
				    #"Added Custom3" = Table.AddColumn(#"Changed Type3", "Quarter Offset", each (([Year]-Date.Year(Today))*4)
				+([Quarter]-Date.QuarterOfYear(Today))),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Added Custom3",{{"Quarter Offset", Int64.Type}}),
				    #"Added Custom4" = Table.AddColumn(#"Changed Type4", "Year-Month", each Date.ToText([Date],"MMM yyyy")),
				    #"Added Custom5" = Table.AddColumn(#"Added Custom4", "Year-Month Code", each Date.ToText([Date],"yyyyMM")),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Added Custom5",{{"Year-Month", type text}, {"Year-Month Code", Int64.Type}})
				in
				    #"Changed Type5"

	annotation PBI_ResultType = Table

